name: base_multiplatform_project
description: "Template for flutter projects"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Images
  cached_network_image: ^3.3.1

  # Network
  dio: any

  # DB (Floor)
  floor: any
  sqflite: any
  path: any

  # DI
  get_it: any
  injectable: any

  # State
  flutter_riverpod: any

  # Models / sealed classes / json
  freezed_annotation: any
  json_annotation: any

  # Splash
  flutter_native_splash: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: any
  json_serializable: any
  injectable_generator: any
  floor_generator: any
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans_regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans_bold.ttf
          weight: 700